### ISSUE TITLE
ENV for enabling preview missing

### ISSUE THREAD

**Issue by HonzaStefanik** [ButterCMS/buttercms-java#8]
The SDK should be able to be configured via an ENV to allow / disable the preview function like in the [react starter project for example](https://github.com/ButterCMS/react-starter-buttercms/blob/main/src/utils/buttercmssdk.js)

**Comment by martinalbert** [comment]
@ViolanteCodes this was fixed by https://github.com/ButterCMS/buttercms-java/commit/a74bcf183ba090a9bb25a3ea59b354e8ddfa639b
